env:
- COVERAGE: true
language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
install:
- mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test jacoco:report
after_success:
- mvn coveralls:report
notifications:
  email: false
  slack: scriptkitty:chR3j2XFxzsbXgjC6p1jJ2is
