name: test-workflow
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup-maven
        id: setup-maven
        uses: s4u/setup-maven-action@v1.7.0
        with:
          java-version: 17
          maven-version: 3.9.0
      - name: maven
        run: mvn -B -V help:active-profiles
