name: test-workflow
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          cache: 'maven'
          distribution: 'corretto'
          java-version: '17'
      - name: Run maven
        run: mvn -V

